# Generated by Django 5.1.7 on 2025-03-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=11)),
                ('yearofstudy', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('bloodgroup', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('mothertongue', models.CharField(max_length=50)),
                ('aadhaar', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('iscompleted', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
